services:

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=default

  postgres:
    image: 'postgres:14-alpine3.16'
    environment:
      - 'POSTGRES_DB=wmb'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5435:5432'