services:
  app:
    image: 'openjdk:17.0.1-slim-bullseye'

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=wmb'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5435:5432'