services:

  wmb-webapp:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
     - wmb-postgres

    ports:
     - '8080:8080'

    env_file:
      - .env

    volumes:
      - web_images:/home/enigma/IdeaProjects/wmb_images

    networks:
      - front-tier
      - back-tier

  wmb-postgres:
    image: 'postgres:14-alpine3.16'
    env_file:
      - .env

    ports:
      - '5434:5432'

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - back-tier

volumes:
  web_images:
  db_data:

networks:
  front-tier:
  back-tier: